# Generated by Django 4.0.6 on 2022-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=1000)),
                ('ir_date', models.DateField(db_index=True)),
                ('total_revenue', models.BigIntegerField(db_index=True)),
                ('operating_income', models.BigIntegerField(db_index=True)),
                ('net_income', models.BigIntegerField(db_index=True)),
                ('assets', models.BigIntegerField(db_index=True)),
                ('liabilities', models.BigIntegerField(db_index=True)),
                ('equities', models.BigIntegerField(db_index=True)),
                ('operating_cf', models.BigIntegerField(db_index=True)),
                ('investment_cf', models.BigIntegerField(db_index=True)),
                ('finance_cf', models.BigIntegerField(db_index=True)),
                ('stock_price', models.BigIntegerField(db_index=True)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_finance',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('market_code', models.CharField(max_length=100)),
                ('next_ir_date', models.DateField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
    ]
