# Generated by Django 4.0.6 on 2022-08-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyfinance',
            table='company_finance',
        ),
        migrations.AlterModelTable(
            name='companymaster',
            table='company_master',
        ),
    ]
